name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch name if different
  workflow_dispatch:  # Allows manual trigger

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or '18' depending on your Next.js version
          cache: 'npm'
          cache-dependency-path: './mui-theme/package-lock.json'  # Adjust if needed

      - name: Install dependencies for Next.js project
        working-directory: ./mui-theme
        run: npm ci

      - name: Build Next.js project
        working-directory: ./mui-theme
        run: npm run build
        env:
          # Important for Next.js static export with subdirectory
          NEXT_PUBLIC_BASE_PATH: /mui-theme

      - name: Export Next.js as static site
        working-directory: ./mui-theme
        run: npm run export || echo "No export script, using build output"

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          # Copy root HTML files
          cp index.html deploy/ 2>/dev/null || true
          cp -r *.html deploy/ 2>/dev/null || true
          cp -r css deploy/ 2>/dev/null || true
          cp -r js deploy/ 2>/dev/null || true
          cp -r images deploy/ 2>/dev/null || true
          cp -r assets deploy/ 2>/dev/null || true
          # Add any other static files/folders from root
          
      - name: Copy Next.js build to mui-theme directory
        run: |
          mkdir -p deploy/mui-theme
          # Copy Next.js static export (out directory by default)
          cp -r mui-theme/out/* deploy/mui-theme/ 2>/dev/null || \
          cp -r mui-theme/.next/static deploy/mui-theme/ 2>/dev/null || \
          cp -r mui-theme/build/* deploy/mui-theme/ 2>/dev/null || true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4